In [1]:
import pandas as pd

df = pd.read_csv('各鄉鎮市區人口密度.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             375 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [2]:
df.iloc[:10]

  statistic_yyy site_id people_total      area population_density
0           統計年     區域別        年底人口數      土地面積               人口密度
1           106  新北市板橋區       551480   23.1373              23835
2           106  新北市三重區       387484    16.317              23747
3           106  新北市中和區       413590    20.144              20532
4           106  新北市永和區       222585    5.7138              38956
5           106  新北市新莊區       416524   19.7383              21102
6           106  新北市新店區       302089  120.2255               2513
7           106  新北市樹林區       184149   33.1288               5559
8           106  新北市鶯歌區        86593   21.1248               4099
9           106  新北市三峽區       114926  191.4508                600

In [6]:
df.iloc[-10:]

,statistic_yyy,site_id,people_total,area,population_density
366,106,連江縣北竿鄉,2360,9.9,238
367,106,連江縣莒光鄉,1624,4.7,346
368,106,連江縣東引鄉,1352,3.8,356
369,106,東沙群島,…,2.38,…
370,106,南沙群島,…,0.5045,…
371,NaN,NaN,NaN,NaN,NaN
372,NaN,說明：1.人口密度係指每單位土地面積內之人口數。,NaN,NaN,NaN
373,NaN,2.96年12月起，我國土地面積增列東沙群島(2.38平方公里)及南沙群島(0.4896平方公里),NaN,NaN,NaN
374,NaN,，由高雄市代管；原金門縣烏坵鄉面積，因重測由2.6平方公里修正為1.2平方公里。,NaN,NaN,NaN
375,NaN,3.104年12月南沙太平島交通基礎整建工程竣工，增加面積0.0149平方公里。,NaN,NaN,NaN

In [8]:
df1 = df.dropna()
df1.info()
df1.tail()
df1.head()

<class 'pandas.core.frame.DataFrame'>
Index: 371 entries, 0 to 370
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             371 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 17.4+ KB

  statistic_yyy site_id people_total     area population_density
0           統計年     區域別        年底人口數     土地面積               人口密度
1           106  新北市板橋區       551480  23.1373              23835
2           106  新北市三重區       387484   16.317              23747
3           106  新北市中和區       413590   20.144              20532
4           106  新北市永和區       222585   5.7138              38956

In [9]:
df1.head()

  statistic_yyy site_id people_total     area population_density
0           統計年     區域別        年底人口數     土地面積               人口密度
1           106  新北市板橋區       551480  23.1373              23835
2           106  新北市三重區       387484   16.317              23747
3           106  新北市中和區       413590   20.144              20532
4           106  新北市永和區       222585   5.7138              38956

In [12]:
df2 = df1.rename(columns=df1.iloc[0].to_dict())
df2

     統計年     區域別   年底人口數     土地面積   人口密度
0    統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[371 rows x 5 columns]

In [14]:
df3 = df2.drop(index=0)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 17.3+ KB

In [15]:
import numpy as np
def str_to_int(value:str) ->int:
    return value

df3['年底人口數'].map(str_to_int)

1      551480
2      387484
3      413590
4      222585
5      416524
        ...
366      2360
367      1624
368      1352
369        …
370        …
Name: 年底人口數, Length: 370, dtype: object

In [18]:
import numpy as np
def str_to_int(value:str) ->int:
    try:
        value_int = int(value)
    except:
        value_int = 0
    return value_int

def str_to_float(valu:str) ->float:
    try:
        value_float = float(value)
    except:
        value_float = 0
    return value_float

df3['年底人口數'] = df3['年底人口數'].map(str_to_int)
df3['人口密度'] = df3['人口密度'].map(str_to_int)
df3['土地面積'] = df3['土地面積'].map(str_to_float)

In [20]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    int64
 4   人口密度    370 non-null    int64
dtypes: int64(3), object(2)
memory usage: 17.3+ KB

In [22]:
df3

     統計年     區域別   年底人口數  土地面積   人口密度
1    106  新北市板橋區  551480     0  23835
2    106  新北市三重區  387484     0  23747
3    106  新北市中和區  413590     0  20532
4    106  新北市永和區  222585     0  38956
5    106  新北市新莊區  416524     0  21102
..   ...     ...     ...   ...    ...
366  106  連江縣北竿鄉    2360     0    238
367  106  連江縣莒光鄉    1624     0    346
368  106  連江縣東引鄉    1352     0    356
369  106    東沙群島       0     0      0
370  106    南沙群島       0     0      0

[370 rows x 5 columns]

In [32]:
def split(value:str) -> str:
    if len(value) > 4:
        return value[:3]
    else:
        return value
    
df3['縣市'] = df3['區域別'].map(split)

In [27]:
df4 = df3.reindex(columns=['縣市','區域別','年底人口數','土地面積','人口密度'])
df4

       縣市     區域別   年底人口數  土地面積   人口密度
1     新北市  新北市板橋區  551480     0  23835
2     新北市  新北市三重區  387484     0  23747
3     新北市  新北市中和區  413590     0  20532
4     新北市  新北市永和區  222585     0  38956
5     新北市  新北市新莊區  416524     0  21102
..    ...     ...     ...   ...    ...
366   連江縣  連江縣北竿鄉    2360     0    238
367   連江縣  連江縣莒光鄉    1624     0    346
368   連江縣  連江縣東引鄉    1352     0    356
369  東沙群島    東沙群島       0     0      0
370  南沙群島    南沙群島       0     0      0

[370 rows x 5 columns]

In [31]:
def population(value:int) -> str:
    if value > 367653:
        return '人多'
    elif value > 183826:
        return '適中'
    else:
        return '人少'
    
df4['人口分佈'] = df4['年底人口數'].map(population)
df4

       縣市     區域別   年底人口數  土地面積   人口密度 人口分佈
1     新北市  新北市板橋區  551480     0  23835   人多
2     新北市  新北市三重區  387484     0  23747   人多
3     新北市  新北市中和區  413590     0  20532   人多
4     新北市  新北市永和區  222585     0  38956   適中
5     新北市  新北市新莊區  416524     0  21102   人多
..    ...     ...     ...   ...    ...  ...
366   連江縣  連江縣北竿鄉    2360     0    238   人少
367   連江縣  連江縣莒光鄉    1624     0    346   人少
368   連江縣  連江縣東引鄉    1352     0    356   人少
369  東沙群島    東沙群島       0     0      0   人少
370  南沙群島    南沙群島       0     0      0   人少

[370 rows x 6 columns]

In [29]:
pd.cut(df4['年底人口數'],bins=3)

1        (367653.333, 551480.0]
2        (367653.333, 551480.0]
3        (367653.333, 551480.0]
4      (183826.667, 367653.333]
5        (367653.333, 551480.0]
                 ...
366       (-551.48, 183826.667]
367       (-551.48, 183826.667]
368       (-551.48, 183826.667]
369       (-551.48, 183826.667]
370       (-551.48, 183826.667]
Name: 年底人口數, Length: 370, dtype: category
Categories (3, interval[float64, right]): [(-551.48, 183826.667] < (183826.667, 367653.333] < (367653.333, 551480.0]]

In [33]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/conda/lib/python3.12/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: pandas>=1.2 in /opt/conda/lib/python3.12/site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/conda/lib/python3.12/site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.