In [1]:
import pandas as pd

df = pd.read_csv('各鄉鎮市區人口密度.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             375 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 14.8+ KB

In [2]:
df1 = df.dropna()
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 371 entries, 0 to 370
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   statistic_yyy       371 non-null    object
 1   site_id             371 non-null    object
 2   people_total        371 non-null    object
 3   area                371 non-null    object
 4   population_density  371 non-null    object
dtypes: object(5)
memory usage: 17.4+ KB

In [3]:
df2 = df1.rename(columns = df1.iloc[0].to_dict())
df2

     統計年     區域別   年底人口數     土地面積   人口密度
0    統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[371 rows x 5 columns]

In [4]:
df3 = df2.drop(index=0)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 17.3+ KB

In [5]:
import numpy as np
def str_to_int(value:str) ->int:
    try:
        value_int = int(value)
    except:
        value_int = 0
    return value_int

def str_to_float(value:str) ->float:
    try:
        value_float = float(value)
    except:
        value_float = 0
    return value_float


df3['年底人口數'] = df3['年底人口數'].map(str_to_int)
df3['人口密度'] = df3['人口密度'].map(str_to_int)
df3['土地面積'] = df3['土地面積'].map(str_to_float)

In [7]:
df3.info()
df3.head()

<class 'pandas.core.frame.DataFrame'>
Index: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    float64
 4   人口密度    370 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 17.3+ KB

   統計年     區域別   年底人口數     土地面積   人口密度
1  106  新北市板橋區  551480  23.1373  23835
2  106  新北市三重區  387484  16.3170  23747
3  106  新北市中和區  413590  20.1440  20532
4  106  新北市永和區  222585   5.7138  38956
5  106  新北市新莊區  416524  19.7383  21102

In [9]:
def splite(value:str) ->str:
    if len(value) > 4 :
        return value[:3]
    else:
        return value
df3['縣市'] = df3['區域別'].map(splite)
df3

     統計年     區域別   年底人口數     土地面積   人口密度    縣市
1    106  新北市板橋區  551480  23.1373  23835   新北市
2    106  新北市三重區  387484  16.3170  23747   新北市
3    106  新北市中和區  413590  20.1440  20532   新北市
4    106  新北市永和區  222585   5.7138  38956   新北市
5    106  新北市新莊區  416524  19.7383  21102   新北市
..   ...     ...     ...      ...    ...   ...
366  106  連江縣北竿鄉    2360   9.9000    238   連江縣
367  106  連江縣莒光鄉    1624   4.7000    346   連江縣
368  106  連江縣東引鄉    1352   3.8000    356   連江縣
369  106    東沙群島       0   2.3800      0  東沙群島
370  106    南沙群島       0   0.5045      0  南沙群島

[370 rows x 6 columns]

In [10]:
df3.groupby('縣市')[['年底人口數','土地面積']].sum()

        年底人口數       土地面積
縣市
南投縣    501051  4106.4360
南沙群島        0     0.5045
嘉義市    269398    60.0256
嘉義縣    511182  1903.6367
基隆市    371458   132.7589
宜蘭縣    456607  2143.6251
屏東縣    829939  2775.6003
彰化縣   1282458  1074.3960
新北市   3986689  2052.5667
新竹市    441132   104.1526
新竹縣    552169  1427.5369
東沙群島        0     2.3800
桃園市   2188017  1220.9540
澎湖縣    104073   126.8641
臺中市   2787070  2214.8968
臺北市   2683257   271.7997
臺南市   1886522  2191.6531
臺東縣    219540  3515.2526
花蓮縣    329237  4628.5714
苗栗縣    553807  1820.3149
連江縣     12880    28.8000
金門縣    137456   151.6560
雲林縣    690373  1290.8326
高雄市   2776912  2951.8524

In [11]:
df3.groupby('縣市')[['年底人口數','土地面積']].agg(['sum','mean'])

        年底人口數                      土地面積
          sum           mean        sum        mean
縣市
南投縣    501051   38542.384615  4106.4360  315.879692
南沙群島        0       0.000000     0.5045    0.504500
嘉義市    269398  134699.000000    60.0256   30.012800
嘉義縣    511182   28399.000000  1903.6367  105.757594
基隆市    371458   53065.428571   132.7589   18.965557
宜蘭縣    456607   38050.583333  2143.6251  178.635425
屏東縣    829939   25149.666667  2775.6003   84.109100
彰化縣   1282458   49325.307692  1074.3960   41.322923
新北市   3986689  137472.034483  2052.5667   70.778162
新竹市    441132  147044.000000   104.1526   34.717533
新竹縣    552169   42474.538462  1427.5369  109.810531
東沙群島        0       0.000000     2.3800    2.380000
桃園市   2188017  168309.000000  1220.9540   93.919538
澎湖縣    104073   17345.500000   126.8641   21.144017
臺中市   2787070   96105.862069  2214.8968   76.375752
臺北市   2683257  223604.750000   271.7997   22.649975
臺南市   1886522   50987.081081  2191.6531   59.233868
臺東縣    219540   13721.250000  3515.2526  219.703287
花蓮縣    329237   25325.923077  4628.5714  356.043954
苗栗縣    553807   30767.055556  1820.3149  101.128606
連江縣     12880    3220.000000    28.8000    7.200000
金門縣    137456   22909.333333   151.6560   25.276000
雲林縣    690373   34518.650000  1290.8326   64.541630
高雄市   2776912   73076.631579  2951.8524   77.680326